# 1Password
ACCOUNT_SHORTHAND = "my"
VAULT_ITEM_NAME = "EncryptionSecrets"
SESSION_CACHE_FILE = ".session_token"

# 1Password Field Labels
FIELD_ENCRYPTION_PASS = "ENCRYPTION_PASS"
FIELD_INPUT_LOCATION = "INPUT_LOCATION"
FIELD_OUTPUT_LOCATION = "OUTPUT_LOCATION"
FIELD_DECRYPTED_OUTPUT_LOCATION = "DECRYPTED_OUTPUT_LOCATION"
